// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAk0pX-BlEfzwoE_J2zFXQTxp7AgCAa6g',
    appId: '1:165018223192:web:4f0118199dd93edc0fc02d',
    messagingSenderId: '165018223192',
    projectId: 'ac7marcivet',
    authDomain: 'ac7marcivet.firebaseapp.com',
    storageBucket: 'ac7marcivet.appspot.com',
    measurementId: 'G-TPVESKVFTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3_t7o3pyL-eTOZKH48NHSh-lfOFZZmQo',
    appId: '1:165018223192:android:765669be2de9cb7b0fc02d',
    messagingSenderId: '165018223192',
    projectId: 'ac7marcivet',
    storageBucket: 'ac7marcivet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVdxnwzKImeMPJH_3lE4irA6F5FbwjcNY',
    appId: '1:165018223192:ios:b8715e70a70e24f10fc02d',
    messagingSenderId: '165018223192',
    projectId: 'ac7marcivet',
    storageBucket: 'ac7marcivet.appspot.com',
    iosBundleId: 'com.example.ac7',
  );
}
